// <auto-generated />
using Cafe.Configuration.Infrastructure.EFcore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cafe.Configuration.Infrastructure.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20210407052834_CofeeMigration8")]
    partial class CofeeMigration8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.CoffeeGrower", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoffeeGrowers");
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.ConfigurationCrop", b =>
                {
                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemperatureId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropId");

                    b.ToTable("ConfigurationCrops");
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.Crop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoffeeGrowerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConfigurationCropId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayFormation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeGrowerId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.Temperature", b =>
                {
                    b.Property<string>("ConfigurationCropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaximunThresholdInsectDevelioment")
                        .HasColumnType("float");

                    b.Property<double>("MinimumEffectiveGrade")
                        .HasColumnType("float");

                    b.Property<double>("MinimumThresholdInsectDevelopment")
                        .HasColumnType("float");

                    b.HasKey("ConfigurationCropId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.ConfigurationCrop", b =>
                {
                    b.HasOne("Cafe.Configuration.Domain.Entities.Crop", "Crop")
                        .WithOne("ConfigurationCrop")
                        .HasForeignKey("Cafe.Configuration.Domain.Entities.ConfigurationCrop", "CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.Crop", b =>
                {
                    b.HasOne("Cafe.Configuration.Domain.Entities.CoffeeGrower", "CoffeeGrower")
                        .WithMany("Crops")
                        .HasForeignKey("CoffeeGrowerId");
                });

            modelBuilder.Entity("Cafe.Configuration.Domain.Entities.Temperature", b =>
                {
                    b.HasOne("Cafe.Configuration.Domain.Entities.ConfigurationCrop", "ConfigurationCrop")
                        .WithOne("Temperature")
                        .HasForeignKey("Cafe.Configuration.Domain.Entities.Temperature", "ConfigurationCropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
